service: pool-temp

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource:
      - "arn:aws:s3:::pool-temperatures/*"
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
    Resource:
      - "arn:aws:s3:::pool-temperatures/*"

functions:
  ingestTweet:
    handler: handler.ingestTweet
    timeout: 30
    environment: ${file(.env.yml)}
    events:
      - http:
          path: /ingest-tweet
          method: post
          private: false
  refreshTweet:
      handler: handler.refreshTweet
      timeout: 30
      events:
        - schedule: cron(0 3 * * ? *)

