service: pool-temp

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource:
      - "arn:aws:s3:::pool-temperatures/*"
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
    Resource:
      - "arn:aws:s3:::pool-temperatures/*"

functions:
  ingestTweet:
    handler: src/handler.ingestTweet
    timeout: 30
    events:
      - http:
          path: /ingest-tweet
          method: post
          private: false
  refreshLatestReading:
      handler: src/handler.refreshLatestReading
      timeout: 30
      events:
        - schedule: cron(0 3 * * ? *)

